version: '3'

services:
  loginserver:
    build: ./login
    volumes:
      - .:/usr/src/loginserver
    ports:
      - "2106:2106"
  gameserver:
    build: ./game
    volumes:
      - .:/usr/src/gameserver
    ports:
      - "7777:7777"
