version: '3'

services:
  login_server:
    build: .
    command: make && ./build/login_server
    ports:
      - 2106:2106
  game_server:
    build: .
    command: make && ./build/game_server
    ports:
      - 7777:7777
