version: '3'

services:
  loginserver:
    build: .
    command: bash ./compile_and_run_ls.sh
    volumes:
      - ./login:/usr/src/l2auth/login
    ports:
      - 2106:2106
  gameserver:
    build: .
    command: bash ./compile_and_run_gs.sh
    volumes:
      - ./game:/usr/src/l2auth/game
    ports:
      - 7777:7777
